version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  api:
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo_db
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile

networks:
  backend:
    name: backend

volumes:
  mongo_db: {}