version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_db:/data/db
    #ports:
      #- "2717:27017"
    networks:
      - backend

  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    networks:
      - backend

networks:
  backend:
    name: backend

volumes:
  mongo_db: {}